function [ C ] = GeneratingExamples2(n,m)
%GENERATINGEXAMPLES2 此处显示有关此函数的摘要
%   此处显示详细说明
C = cell(3,m);
lambda = 1.3;
gamma = 5;

%%   First generate the initial ellipsoid 
% 
mu = 0;
var = 5;
for k=1:m
    B1 = normrnd(mu,var,n,n);
    % B1 is a sparse matrix with sparsity density p=2/n which
    %   will be generated by standard normal distributed.
    for i=1:n
        % make sure that B1 is a sparse matrix
        for j=1:n
            if B1(i,j)>=2/n;
                B1(i,j) = 0;
            end
        end
    end
    A1 = gamma*eye(n)+B1'*B1;
    b1 = rand(n,1);
    alpha1 = 1+b1'*A1*b1;

    C{1,k} = A1;
    C{2,k} = b1;
    C{3,k} = alpha1;
end
end

